### ISSUE TITLE
Just crashes on nil first load.

### ISSUE THREAD

**Issue by simplegray** [jeffbarg/SwipeView#7]

**Comment by MattMarji** [comment]
Seems like the images were forgotten during the last commit, just download and include images with the matching names and it will work.
![finn](https://cloud.githubusercontent.com/assets/6507144/15056203/6abe6430-12de-11e6-9422-adf37dd1dddc.png)
![fiona](https://cloud.githubusercontent.com/assets/6507144/15056204/6abe1e6c-12de-11e6-9386-1062e1bbbc50.png)
![jake](https://cloud.githubusercontent.com/assets/6507144/15056202/6abe562a-12de-11e6-951b-0647eeeb0508.png)
![prince](https://cloud.githubusercontent.com/assets/6507144/15056201/6abe1f0c-12de-11e6-9d7a-d21235c82fba.png)

**Comment by jeffbarg** [comment]
I checked recently, looks like the package still runs and compiles without issue.  Please reopen the issue if it reoccurs.
